package io.github.pyth0n14n.tastinggenie.domain.model

import io.github.pyth0n14n.tastinggenie.domain.model.enums.Aroma

enum class AromaTaste(
    val label: String,
) {
    SWEET("甘味"),
    SOUR("酸味"),
    BITTER_ASTRINGENT("苦味・渋味"),
    UMAMI("旨味"),
    OTHER("その他"),
}

enum class AromaComponent(
    val label: String,
    val description: String,
    val adjectives: String,
) {
    GINJO(
        label = "吟醸香",
        description = "酵母由来。主に薫酒に見られる要素",
        adjectives = "華やか、フルーティー、爽やか、清涼、みずみずしい",
    ),
    RAW_MATERIAL(
        label = "原料香",
        description = "原料由来。主に醇酒に見られる要素",
        adjectives = "ふくよか、ふくらみ、まろやか、なめらか",
    ),
    AGED(
        label = "熟成香",
        description = "熟成由来。主に熟酒に見られる要素",
        adjectives = "力強い、複雑、個性的、凝縮感、ボリューム感",
    ),
}

data class AromaMasterEntry(
    val aroma: Aroma,
    val label: String,
    val taste: AromaTaste,
    val component: AromaComponent,
    val category: String,
)

val AromaMasterEntries: List<AromaMasterEntry> =
    listOf(
        entry(Aroma.JAPANESE_PEAR, "梨", AromaTaste.SWEET, AromaComponent.GINJO, "果実類"),
        entry(Aroma.WHITE_PEACH, "白桃", AromaTaste.SWEET, AromaComponent.GINJO, "果実類"),
        entry(Aroma.APPLE, "リンゴ", AromaTaste.SWEET, AromaComponent.GINJO, "果実類"),
        entry(Aroma.MIKAN, "みかん", AromaTaste.SWEET, AromaComponent.GINJO, "果実類"),
        entry(Aroma.MUSCAT, "マスカット", AromaTaste.SWEET, AromaComponent.GINJO, "果実類"),
        entry(Aroma.MELON, "メロン", AromaTaste.SWEET, AromaComponent.GINJO, "果実類"),
        entry(Aroma.BANANA, "バナナ", AromaTaste.SWEET, AromaComponent.GINJO, "果実類"),
        entry(Aroma.PAPAYA, "パパイヤ", AromaTaste.SWEET, AromaComponent.GINJO, "果実類"),
        entry(Aroma.APRICOT, "アプリコット", AromaTaste.SWEET, AromaComponent.GINJO, "果実類"),
        entry(Aroma.PEAR, "洋梨", AromaTaste.SWEET, AromaComponent.GINJO, "果実類"),
        entry(Aroma.MANGO, "マンゴ", AromaTaste.SWEET, AromaComponent.GINJO, "果実類"),
        entry(Aroma.LYCHEE, "ライチ", AromaTaste.SWEET, AromaComponent.GINJO, "果実類"),
        entry(Aroma.UME_FLOWER, "梅", AromaTaste.SWEET, AromaComponent.GINJO, "花類"),
        entry(Aroma.ACACIA, "アカシア", AromaTaste.SWEET, AromaComponent.GINJO, "花類"),
        entry(Aroma.ORANGE_BLOSSOM, "オレンジ(花)", AromaTaste.SWEET, AromaComponent.GINJO, "花類"),
        entry(Aroma.MILK_VETCH, "レンゲ", AromaTaste.SWEET, AromaComponent.GINJO, "花類"),
        entry(Aroma.LILY, "ユリ", AromaTaste.SWEET, AromaComponent.GINJO, "花類"),
        entry(Aroma.LAVENDER, "ラベンダー", AromaTaste.SWEET, AromaComponent.GINJO, "花類"),
        entry(Aroma.ROSE, "バラ", AromaTaste.SWEET, AromaComponent.GINJO, "花類"),
        entry(Aroma.OSMANTHUS, "キンモクセイ", AromaTaste.SWEET, AromaComponent.GINJO, "花類"),
        entry(Aroma.CYCLAMEN, "シクラメン", AromaTaste.SWEET, AromaComponent.GINJO, "花類"),
        entry(Aroma.WHITE_SUGAR, "白砂糖", AromaTaste.SWEET, AromaComponent.RAW_MATERIAL, "菓子類"),
        entry(Aroma.HOSHII_AME, "干飯飴", AromaTaste.SWEET, AromaComponent.RAW_MATERIAL, "菓子類"),
        entry(Aroma.MARSHMALLOW, "マシュマロ", AromaTaste.SWEET, AromaComponent.RAW_MATERIAL, "菓子類"),
        entry(Aroma.KONPEITO, "こんぺいとう", AromaTaste.SWEET, AromaComponent.RAW_MATERIAL, "菓子類"),
        entry(Aroma.NERIAME, "練飴", AromaTaste.SWEET, AromaComponent.RAW_MATERIAL, "菓子類"),
        entry(Aroma.WARABI_MOCHI, "わらび餅", AromaTaste.SWEET, AromaComponent.RAW_MATERIAL, "菓子類"),
        entry(Aroma.SAKURA_MOCHI, "桜餅", AromaTaste.SWEET, AromaComponent.RAW_MATERIAL, "菓子類"),
        entry(Aroma.FRESH_CREAM_SWEET_RAW, "生クリーム", AromaTaste.SWEET, AromaComponent.RAW_MATERIAL, "乳製品類"),
        entry(Aroma.CUSTARD_CREAM_SWEET_RAW, "カスタードクリーム", AromaTaste.SWEET, AromaComponent.RAW_MATERIAL, "乳製品類"),
        entry(Aroma.ZARAME, "ザラメ", AromaTaste.SWEET, AromaComponent.AGED, "糖蜜類など"),
        entry(Aroma.BROWN_SUGAR, "黒糖", AromaTaste.SWEET, AromaComponent.AGED, "糖蜜類など"),
        entry(Aroma.KUROMITSU, "黒蜜", AromaTaste.SWEET, AromaComponent.AGED, "糖蜜類など"),
        entry(Aroma.MAPLE_SYRUP, "メープルシロップ", AromaTaste.SWEET, AromaComponent.AGED, "糖蜜類など"),
        entry(Aroma.CARAMEL, "カラメル", AromaTaste.SWEET, AromaComponent.AGED, "糖蜜類など"),
        entry(Aroma.HONEY, "蜂蜜", AromaTaste.SWEET, AromaComponent.AGED, "糖蜜類など"),
        entry(Aroma.VANILLA, "バニラ", AromaTaste.SWEET, AromaComponent.AGED, "糖蜜類など"),
        entry(Aroma.GREEN_UME, "青梅", AromaTaste.SOUR, AromaComponent.GINJO, "果実類"),
        entry(Aroma.YUZU, "柚子", AromaTaste.SOUR, AromaComponent.GINJO, "果実類"),
        entry(Aroma.SUDACHI, "スダチ", AromaTaste.SOUR, AromaComponent.GINJO, "果実類"),
        entry(Aroma.KABOSU, "カボス", AromaTaste.SOUR, AromaComponent.GINJO, "果実類"),
        entry(Aroma.LEMON, "レモン", AromaTaste.SOUR, AromaComponent.GINJO, "果実類"),
        entry(Aroma.LIME, "ライム", AromaTaste.SOUR, AromaComponent.GINJO, "果実類"),
        entry(Aroma.GREEN_APPLE, "青リンゴ", AromaTaste.SOUR, AromaComponent.GINJO, "果実類"),
        entry(Aroma.GRAPEFRUIT, "グレープフルーツ", AromaTaste.SOUR, AromaComponent.GINJO, "果実類"),
        entry(Aroma.ORANGE, "オレンジ", AromaTaste.SOUR, AromaComponent.GINJO, "果実類"),
        entry(Aroma.YOGURT, "ヨーグルト", AromaTaste.SOUR, AromaComponent.RAW_MATERIAL, "乳製品類"),
        entry(Aroma.COTTAGE_CHEESE, "カッテージチーズ", AromaTaste.SOUR, AromaComponent.RAW_MATERIAL, "乳製品類"),
        entry(Aroma.RAISIN, "干しぶどう", AromaTaste.SOUR, AromaComponent.AGED, "ドライフルーツ類"),
        entry(Aroma.DRIED_FIG, "干しいちじく", AromaTaste.SOUR, AromaComponent.AGED, "ドライフルーツ類"),
        entry(Aroma.DRIED_APRICOT, "干し杏", AromaTaste.SOUR, AromaComponent.AGED, "ドライフルーツ類"),
        entry(Aroma.DRIED_PRUNE, "ドライプルーン", AromaTaste.SOUR, AromaComponent.AGED, "ドライフルーツ類"),
        entry(Aroma.CRESS, "クレソン", AromaTaste.BITTER_ASTRINGENT, AromaComponent.GINJO, "菜類および根菜類"),
        entry(Aroma.MITSUBA, "三つ葉", AromaTaste.BITTER_ASTRINGENT, AromaComponent.GINJO, "菜類および根菜類"),
        entry(Aroma.RADISH, "ラディッシュ", AromaTaste.BITTER_ASTRINGENT, AromaComponent.GINJO, "菜類および根菜類"),
        entry(Aroma.GOURD, "瓜", AromaTaste.BITTER_ASTRINGENT, AromaComponent.GINJO, "菜類および根菜類"),
        entry(Aroma.WILD_VEGETABLE, "山菜", AromaTaste.BITTER_ASTRINGENT, AromaComponent.GINJO, "菜類および根菜類"),
        entry(Aroma.TURNIP, "カブラ", AromaTaste.BITTER_ASTRINGENT, AromaComponent.GINJO, "菜類および根菜類"),
        entry(Aroma.DAIKON, "大根", AromaTaste.BITTER_ASTRINGENT, AromaComponent.GINJO, "菜類および根菜類"),
        entry(Aroma.LEMONGRASS, "レモングラス", AromaTaste.BITTER_ASTRINGENT, AromaComponent.GINJO, "香草類および柑橘類の皮類"),
        entry(Aroma.BASIL, "バジル", AromaTaste.BITTER_ASTRINGENT, AromaComponent.GINJO, "香草類および柑橘類の皮類"),
        entry(Aroma.BAY_LEAF, "月桂樹の葉", AromaTaste.BITTER_ASTRINGENT, AromaComponent.GINJO, "香草類および柑橘類の皮類"),
        entry(Aroma.CHERVIL, "セルフィーユ", AromaTaste.BITTER_ASTRINGENT, AromaComponent.GINJO, "香草類および柑橘類の皮類"),
        entry(Aroma.ROSEMARY, "ローズマリー", AromaTaste.BITTER_ASTRINGENT, AromaComponent.GINJO, "香草類および柑橘類の皮類"),
        entry(Aroma.MUGWORT, "ヨモギ", AromaTaste.BITTER_ASTRINGENT, AromaComponent.GINJO, "香草類および柑橘類の皮類"),
        entry(Aroma.PEPPERMINT, "ペパーミント", AromaTaste.BITTER_ASTRINGENT, AromaComponent.GINJO, "香草類および柑橘類の皮類"),
        entry(Aroma.LEMON_PEEL, "レモンの皮", AromaTaste.BITTER_ASTRINGENT, AromaComponent.GINJO, "香草類および柑橘類の皮類"),
        entry(Aroma.LIME_PEEL, "ライムの皮", AromaTaste.BITTER_ASTRINGENT, AromaComponent.GINJO, "香草類および柑橘類の皮類"),
        entry(Aroma.CHESTNUT_SKIN, "栗の皮", AromaTaste.BITTER_ASTRINGENT, AromaComponent.RAW_MATERIAL, "穀物類およびその他"),
        entry(Aroma.PEANUT, "落花生", AromaTaste.BITTER_ASTRINGENT, AromaComponent.RAW_MATERIAL, "穀物類およびその他"),
        entry(Aroma.WALNUT_SKIN, "クルミ", AromaTaste.BITTER_ASTRINGENT, AromaComponent.RAW_MATERIAL, "穀物類およびその他"),
        entry(Aroma.HOOBA, "朴葉", AromaTaste.BITTER_ASTRINGENT, AromaComponent.RAW_MATERIAL, "穀物類およびその他"),
        entry(Aroma.LINDEN, "菩提樹", AromaTaste.BITTER_ASTRINGENT, AromaComponent.AGED, "木類"),
        entry(Aroma.HINOKI, "ヒノキ", AromaTaste.BITTER_ASTRINGENT, AromaComponent.AGED, "木類"),
        entry(Aroma.NARA_OAK, "ナラ", AromaTaste.BITTER_ASTRINGENT, AromaComponent.AGED, "木類"),
        entry(Aroma.OAK, "オーク", AromaTaste.BITTER_ASTRINGENT, AromaComponent.AGED, "木類"),
        entry(Aroma.CASHEW, "カシューナッツ", AromaTaste.BITTER_ASTRINGENT, AromaComponent.AGED, "ナッツ類"),
        entry(Aroma.PEANUT_AGED, "ピーナッツ", AromaTaste.BITTER_ASTRINGENT, AromaComponent.AGED, "ナッツ類"),
        entry(Aroma.PINE_NUT, "松の実", AromaTaste.BITTER_ASTRINGENT, AromaComponent.AGED, "ナッツ類"),
        entry(Aroma.ALMOND, "アーモンド", AromaTaste.BITTER_ASTRINGENT, AromaComponent.AGED, "ナッツ類"),
        entry(Aroma.RAW_RICE, "生米", AromaTaste.UMAMI, AromaComponent.RAW_MATERIAL, "穀物(米)類"),
        entry(Aroma.JOSHINKO, "上新粉", AromaTaste.UMAMI, AromaComponent.RAW_MATERIAL, "穀物(米)類"),
        entry(Aroma.DOMYOJIKO, "道明寺粉", AromaTaste.UMAMI, AromaComponent.RAW_MATERIAL, "穀物(米)類"),
        entry(Aroma.COOKED_RICE, "炊飯", AromaTaste.UMAMI, AromaComponent.RAW_MATERIAL, "穀物(米)類"),
        entry(Aroma.MOCHI, "もち", AromaTaste.UMAMI, AromaComponent.RAW_MATERIAL, "穀物(米)類"),
        entry(Aroma.RICE_BRAN, "糠", AromaTaste.UMAMI, AromaComponent.RAW_MATERIAL, "穀物(米)類"),
        entry(Aroma.RICE_EAR, "稲穂", AromaTaste.UMAMI, AromaComponent.RAW_MATERIAL, "穀物(米)類"),
        entry(Aroma.RICE_KOJI, "米麹", AromaTaste.UMAMI, AromaComponent.RAW_MATERIAL, "穀物(米)類"),
        entry(Aroma.DRIED_SHIITAKE, "干しシイタケ", AromaTaste.UMAMI, AromaComponent.AGED, "出汁製品類および発酵調味料類"),
        entry(Aroma.SOY_SAUCE, "醤油", AromaTaste.UMAMI, AromaComponent.AGED, "出汁製品類および発酵調味料類"),
        entry(Aroma.MISO, "味噌", AromaTaste.UMAMI, AromaComponent.AGED, "出汁製品類および発酵調味料類"),
        entry(Aroma.GREEN_BAMBOO_OTHER_GINJO, "青竹", AromaTaste.OTHER, AromaComponent.GINJO, "植物類など"),
        entry(Aroma.GREEN_BAMBOO_GRASS, "青笹", AromaTaste.OTHER, AromaComponent.GINJO, "植物類など"),
        entry(Aroma.NEW_LEAF, "新芽", AromaTaste.OTHER, AromaComponent.GINJO, "植物類など"),
        entry(Aroma.FRESH_TEA, "新茶", AromaTaste.OTHER, AromaComponent.GINJO, "植物類など"),
        entry(Aroma.PINE_NEEDLE, "杉の葉", AromaTaste.OTHER, AromaComponent.GINJO, "植物類など"),
        entry(Aroma.BUTTER, "バター", AromaTaste.OTHER, AromaComponent.RAW_MATERIAL, "乳製品類"),
        entry(Aroma.FRESH_CREAM_OTHER_RAW, "生クリーム", AromaTaste.OTHER, AromaComponent.RAW_MATERIAL, "乳製品類"),
        entry(Aroma.CUSTARD_CREAM_OTHER_RAW, "カスタードクリーム", AromaTaste.OTHER, AromaComponent.RAW_MATERIAL, "乳製品類"),
        entry(Aroma.WHITE_PEPPER, "白コショウ", AromaTaste.OTHER, AromaComponent.AGED, "スパイス類"),
        entry(Aroma.BLACK_PEPPER, "黒コショウ", AromaTaste.OTHER, AromaComponent.AGED, "スパイス類"),
        entry(Aroma.SANSHO, "山椒", AromaTaste.OTHER, AromaComponent.AGED, "スパイス類"),
        entry(Aroma.CINNAMON, "シナモン", AromaTaste.OTHER, AromaComponent.AGED, "スパイス類"),
        entry(Aroma.CLOVE, "クローブ", AromaTaste.OTHER, AromaComponent.AGED, "スパイス類"),
        entry(Aroma.ANISE, "アニス", AromaTaste.OTHER, AromaComponent.AGED, "スパイス類"),
        entry(Aroma.OOLONG_TEA, "ウーロン茶", AromaTaste.OTHER, AromaComponent.AGED, "茶葉類およびお香類"),
        entry(Aroma.PUER_TEA, "プーアール茶", AromaTaste.OTHER, AromaComponent.AGED, "茶葉類およびお香類"),
        entry(Aroma.BLACK_TEA, "紅茶", AromaTaste.OTHER, AromaComponent.AGED, "茶葉類およびお香類"),
        entry(Aroma.AGARWOOD, "沈香", AromaTaste.OTHER, AromaComponent.AGED, "茶葉類およびお香類"),
        entry(Aroma.AMBERGRIS, "竜涎香", AromaTaste.OTHER, AromaComponent.AGED, "茶葉類およびお香類"),
        entry(Aroma.SHIMEJI, "シメジ", AromaTaste.OTHER, AromaComponent.AGED, "キノコ類および土類"),
        entry(Aroma.MUSHROOM, "マッシュルーム", AromaTaste.OTHER, AromaComponent.AGED, "キノコ類および土類"),
        entry(Aroma.PORCINI, "ポルチーニ", AromaTaste.OTHER, AromaComponent.AGED, "キノコ類および土類"),
        entry(Aroma.TRUFFLE, "トリュフ", AromaTaste.OTHER, AromaComponent.AGED, "キノコ類および土類"),
        entry(Aroma.GOBO, "ゴボウ", AromaTaste.OTHER, AromaComponent.AGED, "キノコ類および土類"),
        entry(Aroma.PEAT, "ピート(泥炭)", AromaTaste.OTHER, AromaComponent.AGED, "キノコ類および土類"),
        entry(Aroma.CANDLE, "ろうそく", AromaTaste.OTHER, AromaComponent.AGED, "油脂類および皮類"),
        entry(Aroma.BEESWAX, "蜜蝋", AromaTaste.OTHER, AromaComponent.AGED, "油脂類および皮類"),
        entry(Aroma.PINE_RESIN, "松ヤニ", AromaTaste.OTHER, AromaComponent.AGED, "油脂類および皮類"),
        entry(Aroma.MUSK, "麝香", AromaTaste.OTHER, AromaComponent.AGED, "油脂類および皮類"),
        entry(Aroma.TANNED_LEATHER, "なめし皮", AromaTaste.OTHER, AromaComponent.AGED, "油脂類および皮類"),
        entry(Aroma.KELP, "昆布", AromaTaste.OTHER, AromaComponent.AGED, "ヨード類"),
        entry(Aroma.NORI_TSUKUDANI, "海苔の佃煮", AromaTaste.OTHER, AromaComponent.AGED, "ヨード類"),
        entry(Aroma.SMOKED_ROASTED_GRAIN, "スモークまたはローストした穀物類", AromaTaste.OTHER, AromaComponent.AGED, "煙香類"),
    )

val AromaLabelByValue: Map<String, String> = AromaMasterEntries.associate { it.aroma.name to it.label }

private fun entry(
    aroma: Aroma,
    label: String,
    taste: AromaTaste,
    component: AromaComponent,
    category: String,
): AromaMasterEntry =
    AromaMasterEntry(
        aroma = aroma,
        label = label,
        taste = taste,
        component = component,
        category = category,
    )
