package io.github.pyth0n14n.tastinggenie.domain.model

enum class ReviewMode(
    val id: String,
) {
    NORMAL("normal"),
    KIKISAKE_SHI("kikisake_shi"),
    DEBUG("debug"),
}

enum class ReviewItemId {
    DATE,
    PRICE,
    VOLUME,
    TEMPERATURE,
    BAR,
    DISH,
    FOOD_COMPATIBILITY,
    APPEARANCE_SOUNDNESS,
    APPEARANCE_COLOR,
    APPEARANCE_VISCOSITY,
    AROMA_SOUNDNESS,
    AROMA_INTENSITY,
    AROMA_EXAMPLES,
    AROMA_MAIN_NOTE,
    AROMA_COMPLEXITY,
    TASTE_SOUNDNESS,
    TASTE_ATTACK,
    TASTE_TEXTURE_ROUNDNESS,
    TASTE_TEXTURE_SMOOTHNESS,
    TASTE_TEXTURE_NOTE,
    TASTE_SWEETNESS,
    TASTE_SOURNESS,
    TASTE_UMAMI,
    TASTE_BITTERNESS,
    TASTE_DESCRIPTION,
    TASTE_SWEET_DRYNESS,
    TASTE_IN_PALATE_AROMA_INTENSITY,
    TASTE_IN_PALATE_AROMA_EXAMPLES,
    TASTE_AFTERTASTE_LENGTH,
    TASTE_AFTERTASTE_NOTE,
    TASTE_COMPLEXITY,
    OTHER_INDIVIDUALITY,
    OTHER_CAUTIONS,
    OTHER_SAKE_TYPES,
    OTHER_FREE_COMMENT,
    OTHER_OVERALL_REVIEW,
}

data class ReviewModeDefinition(
    val id: String,
    val label: String,
    val isBuiltIn: Boolean,
    val enabledItemIds: Set<ReviewItemId>,
)

val normalReviewItemIds: Set<ReviewItemId> =
    setOf(
        ReviewItemId.DATE,
        ReviewItemId.PRICE,
        ReviewItemId.VOLUME,
        ReviewItemId.TEMPERATURE,
        ReviewItemId.BAR,
        ReviewItemId.DISH,
        ReviewItemId.FOOD_COMPATIBILITY,
        ReviewItemId.APPEARANCE_SOUNDNESS,
        ReviewItemId.APPEARANCE_COLOR,
        ReviewItemId.APPEARANCE_VISCOSITY,
        ReviewItemId.AROMA_SOUNDNESS,
        ReviewItemId.AROMA_INTENSITY,
        ReviewItemId.AROMA_EXAMPLES,
        ReviewItemId.AROMA_COMPLEXITY,
        ReviewItemId.TASTE_SOUNDNESS,
        ReviewItemId.TASTE_ATTACK,
        ReviewItemId.TASTE_TEXTURE_ROUNDNESS,
        ReviewItemId.TASTE_TEXTURE_SMOOTHNESS,
        ReviewItemId.TASTE_SWEETNESS,
        ReviewItemId.TASTE_SOURNESS,
        ReviewItemId.TASTE_UMAMI,
        ReviewItemId.TASTE_BITTERNESS,
        ReviewItemId.TASTE_SWEET_DRYNESS,
        ReviewItemId.TASTE_IN_PALATE_AROMA_INTENSITY,
        ReviewItemId.TASTE_IN_PALATE_AROMA_EXAMPLES,
        ReviewItemId.TASTE_AFTERTASTE_LENGTH,
        ReviewItemId.TASTE_COMPLEXITY,
        ReviewItemId.OTHER_INDIVIDUALITY,
        ReviewItemId.OTHER_SAKE_TYPES,
        ReviewItemId.OTHER_FREE_COMMENT,
        ReviewItemId.OTHER_OVERALL_REVIEW,
    )

val kikisakeShiReviewItemIds: Set<ReviewItemId> =
    setOf(
        ReviewItemId.DATE,
        ReviewItemId.PRICE,
        ReviewItemId.VOLUME,
        ReviewItemId.TEMPERATURE,
        ReviewItemId.BAR,
        ReviewItemId.DISH,
        ReviewItemId.FOOD_COMPATIBILITY,
        ReviewItemId.APPEARANCE_SOUNDNESS,
        ReviewItemId.APPEARANCE_COLOR,
        ReviewItemId.APPEARANCE_VISCOSITY,
        ReviewItemId.AROMA_SOUNDNESS,
        ReviewItemId.AROMA_INTENSITY,
        ReviewItemId.AROMA_EXAMPLES,
        ReviewItemId.AROMA_MAIN_NOTE,
        ReviewItemId.TASTE_SOUNDNESS,
        ReviewItemId.TASTE_ATTACK,
        ReviewItemId.TASTE_TEXTURE_NOTE,
        ReviewItemId.TASTE_DESCRIPTION,
        ReviewItemId.TASTE_SWEET_DRYNESS,
        ReviewItemId.TASTE_IN_PALATE_AROMA_INTENSITY,
        ReviewItemId.TASTE_IN_PALATE_AROMA_EXAMPLES,
        ReviewItemId.TASTE_AFTERTASTE_LENGTH,
        ReviewItemId.TASTE_AFTERTASTE_NOTE,
        ReviewItemId.TASTE_COMPLEXITY,
        ReviewItemId.OTHER_INDIVIDUALITY,
        ReviewItemId.OTHER_CAUTIONS,
        ReviewItemId.OTHER_SAKE_TYPES,
        ReviewItemId.OTHER_FREE_COMMENT,
        ReviewItemId.OTHER_OVERALL_REVIEW,
    )

val debugReviewItemIds: Set<ReviewItemId> = ReviewItemId.entries.toSet()

val builtInReviewModeDefinitions: List<ReviewModeDefinition> =
    listOf(
        ReviewModeDefinition(
            id = ReviewMode.NORMAL.id,
            label = "通常",
            isBuiltIn = true,
            enabledItemIds = normalReviewItemIds,
        ),
        ReviewModeDefinition(
            id = ReviewMode.KIKISAKE_SHI.id,
            label = "利酒師",
            isBuiltIn = true,
            enabledItemIds = kikisakeShiReviewItemIds,
        ),
        ReviewModeDefinition(
            id = ReviewMode.DEBUG.id,
            label = "デバッグ",
            isBuiltIn = true,
            enabledItemIds = debugReviewItemIds,
        ),
    )
